import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="keywords"
          content="nextjs, react, javascript, typescript"
        />
        <meta name="author" content="Your Name" />
        <meta name="robots" content="index, follow" />
        <meta
          name="google-site-verification"
          content="your-google-site-verification-code"
        />
        <meta
          name="og:title"
          content="Create Next App"
        />
        <meta
          name="og:description"
          content="Generated by create next app"
        />
        <meta
          name="og:image"
          content="https://yourdomain.com/og-image.png"
        />
        <meta
          name="og:url"
          content="https://yourdomain.com"
        />
        <meta
          name="og:type"
          content="website"
        />
        <meta
          name="twitter:card"
          content="summary_large_image"
        />
        <meta
          name="twitter:title"
          content="Create Next App"
        />
        <meta
          name="twitter:description"
          content="Generated by create next app"
        />
        <meta
          name="twitter:image"
          content="https://yourdomain.com/twitter-image.png"
        />
        <meta
          name="twitter:url"
          content="https://yourdomain.com"
        />
        <meta
          name="twitter:site"
          content="@yourtwitterhandle"
        />
        <meta
          name="twitter:creator"
          content="@yourtwitterhandle"
        />
        <meta
          name="twitter:image:alt"
          content="An image description"
        />
        <meta
          name="twitter:label1"
          content="Written by"
        />
        <meta
          name="twitter:data1"
          content="Your Name"
        />
        <meta
          name="twitter:label2"
          content="Published on"
        />
        <meta
          name="twitter:data2"
          content="Date"
        />
        <meta
          name="twitter:label3"
          content="Reading time"
        />
        <meta
          name="twitter:data3"
          content="5 min read"
        />
        <meta
          name="twitter:label4"
          content="Category"
        />
        <meta
          name="twitter:data4"
          content="Category"
        />
        </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
